### ISSUE TITLE
Config presets base on different test scenarios

### ISSUE THREAD

**Issue by nbouvrette** [nils-hoyer/cypress-fail-on-console-error#109] opened 2022-08-13 04:13 UTC
Great package by the way.

I was wondering, is there a way right now to enable/disable certain exclusions before and after tests?

For example, I would like to test 404 and 500 errors that trigger console logs... but I don't want to exclude these logs for all tests - only for these very specific tests.

**Comment by mirobo** [comment] 2022-08-16 15:14
Based on this plugin I came to a slightly different solution, see https://github.com/nils-hoyer/cypress-fail-on-console-error/issues/47

But it had some drawbacks like you needed to start every test with cy.visit().

Some days ago I changed the approach to the same as @nils-hoyer and got this very simple solution (which doesn't required cy.visit() before each test):


```
support/index.ts.. no additional imports for "sinon" or sinon-chai were required in my case
/**
 * the code inside this file will be loaded in each spec file
 * FAIL_ON_CONSOLE_ERROR will
 * - in "afterEach" hook: detect and collect console errors (which were not excluded by excludeMessagesDefault or excludeMessages)
 * - in "after" hook: let the last test fail if any console errors occurred (if we would let the test fail in the afterEach hook, subsequent tests would be skipped)
 * */
if (Cypress.env('FAIL_ON_CONSOLE_ERROR')) {
  let spy: sinon.SinonSpy;
  Cypress.on('window:before:load', (win) => {
    // we need to use native sinon, because cy.spy will be reset by Cypress between tests
    // this way we can reuse the same spy without having to start each test with cy.visit(..)
    spy = Cypress.sinon.spy(win.console, 'error');
  });

  Cypress.on('command:end', () => {
    if (!spy || spy.callCount < 1) {
      return;
    }
    const exclusions: RegExp[] = Cypress.env('excludeMessages')
      ? [...excludeMessagesDefault, ...Cypress.env('excludeMessages')]
      : excludeMessagesDefault;

    cy.log(`analyzing console errors with exclusions:\r\n${exclusions.join('\r\n')}`);
    let consoleErrorText = '';
    let ignoreError = false;
    spy.getCalls().every((spyCall) => {
      consoleErrorText = spyCall.args.toString();
      ignoreError = exclusions.some((excludeMessage) => excludeMessage.test(consoleErrorText));
      return ignoreError;
    });
    spy.resetHistory();
    if (!ignoreError) {
      throw new Error(`console error occurred: ${JSON.stringify(consoleErrorText, null, 2)}`);
    }
  });
}
```

In every describe or test you could then add "env: { excludeMessages: [/some message/, /another message/]}"

I didn't extend the Cypress-Config-Object for my purpose, but it would be cleaner than using "env". I'm hoping that this feature gets somehow included into this plugin.. didn't have the time yet to create a PR for it :D

Beware that in Cypress < 10 the env variables will spill over into other tests inside the same spec if you run Cypress in open mode..

**Comment by nils-hoyer** [comment] 2022-08-16 18:03
> Great package by the way.
> 
> I was wondering, is there a way right now to enable/disable certain exclusions before and after tests?
> 
> For example, I would like to test 404 and 500 errors that trigger console logs... but I don't want to exclude these logs for all tests - only for these very specific tests.

Thanks for your great feedback @nbouvrette !
Regarding your request, I had to do some analysis. An straight forward solution from mocha hooks could be the following from support/e2e.ts: 

`
import failOnConsoleError from '../../dist/index';
import './commands';

const config = {
    excludeMessages: ['firstError', 'secondError'],
};

beforeEach(() => {
    if (Cypress.currentTest.title == 'test1') {
        failOnConsoleError(disableExcludeMessage(config, 'secondError'));
    } else if (Cypress.currentTest.title == 'test2') {
        failOnConsoleError(enableExcludeMessage(config, 'thirdError'));
    } else {
        failOnConsoleError(config);
    }
});

const disableExcludeMessage = (config, excludeMessageToDisable) => {
    const newExcludeMessages = config.excludeMessages.filter(
        (message) => message != excludeMessageToDisable
    );
    return {
        excludeMessages: newExcludeMessages,
    };
};

const enableExcludeMessage = (config, excludeMessageToEnable) => {
    return {
        excludeMessages: [...config.excludeMessages, excludeMessageToEnable],
    };
};
`

To make it work, one line in have to be added in the plugin. This can be released quickly.
   Cypress.on('window:before:load', (window) => {
        if (spies) return; //have to added
        spies = createSpies(config, window.console);
    });     

Let me know if this is what you are looking for

**Comment by nbouvrette** [comment] 2022-08-17 02:43
Thanks @nils-hoyer - I think the example @mirobo proposed is a bit more maintainable as the configuration can live next to the test rather than in the `e2e` file. At least on my end, I would rather manage this close to the test since they are not global configurations like the current exclusion list.

**Comment by mirobo** [comment] 2022-08-17 08:04
I guess you would have to adapt this logic here for your purpose, because excludeMessagesDefault would get merged with the excludeMessages from "env".

```
    const exclusions: RegExp[] = Cypress.env('excludeMessages')
      ? [...excludeMessagesDefault, ...Cypress.env('excludeMessages')]
      : excludeMessagesDefault;

```

 You may just want to set exclusions completely, if env is present..

```
    const exclusions: RegExp[] = Cypress.env('excludeMessages') as RegExp[] ?? excludeMessagesDefault;

```

**Comment by nils-hoyer** [comment] 2022-08-19 13:11
> Thanks @nils-hoyer - I think the example @mirobo proposed is a bit more maintainable as the configuration can live next to the test rather than in the `e2e` file. At least on my end, I would rather manage this close to the test since they are not global configurations like the current exclusion list.

I totally agree but this solution is not possible with the current tech. design. I will open a discovery to investigate how to bring this into the plugin properly. @nbouvrette 
thanks for the ideas bringing in @mirobo

**Closed** 2022-08-19 13:15 UTC
Labels: enhancement

**Comment by nils-hoyer** [comment] 2022-09-18 14:51
Hi@nbouvrette  @mirobo, 
The feature "set config from test files" is now integrated in the plugin. The documentation with example usage and links can be found in the readme file, section "Set config from cypress test"

let me know if you notice any unexpected behaviour.

**Comment by nbouvrette** [comment] 2022-09-19 14:18
I just scanned through the change - looks good and thanks for adding this @nils-hoyer
